# Generated by Django 4.2 on 2023-04-16 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_created=True)),
                ('ativo', models.BooleanField(default=True)),
                ('numero', models.IntegerField(unique=True)),
                ('nome', models.CharField(blank=True, default='', max_length=100)),
                ('descricao', models.TextField()),
                ('preco_unitario', models.FloatField(default=0.0)),
                ('imagem', models.ImageField(blank=True, default='', upload_to='cardapio/covers/%Y/%m/%d')),
                ('modificado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cardapio.tipoitem')),
            ],
        ),
    ]
