# Generated by Django 4.2 on 2023-04-16 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardapio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemcardapio",
            name="imagem",
            field=models.ImageField(
                blank=True, default="", upload_to="cardapio/covers"
            ),
        ),
    ]
