# Generated by Django 4.2 on 2023-04-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardapio", "0002_alter_itemcardapio_imagem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemcardapio",
            name="criado_em",
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
