# Generated by Django 4.2 on 2023-05-07 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_remove_pedido_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itenspedido',
            name='numero_pedido',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens', to='pedido.pedido'),
        ),
    ]
