# Generated by Django 4.2 on 2023-05-11 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cardapio", "0003_alter_itemcardapio_criado_em"),
        ("pedido", "0004_alter_itenspedido_numero_pedido"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itenspedido",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="cardapio.itemcardapio"
            ),
        ),
        migrations.AlterField(
            model_name="itenspedido",
            name="numero_pedido",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="itens",
                to="pedido.pedido",
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="forma_pagamento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="pedido.formapagamento"
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="pedido.statuspedido"
            ),
        ),
    ]
