# Generated by Django 4.2 on 2023-05-11 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedido", "0006_alter_pedido_forma_pagamento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formapagamento",
            name="situacao",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="statuspedido",
            name="situacao",
            field=models.BooleanField(default=True),
        ),
    ]
