# Generated by Django 4.2 on 2023-05-11 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pedido", "0008_alter_pedido_forma_pagamento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="forma_pagamento",
            field=models.ForeignKey(
                blank=True,
                default="",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pedido.formapagamento",
            ),
        ),
    ]
