# Generated by Django 4.2 on 2023-05-11 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedido", "0009_alter_pedido_forma_pagamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="fechado_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
