# Generated by Django 4.2 on 2023-05-11 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pedido", "0010_pedido_fechado_em"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="fechado_por",
            field=models.ForeignKey(
                blank=True,
                default="",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fechado_por",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
