# Generated by Django 4.2 on 2023-05-11 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pedido", "0011_pedido_fechado_por"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pedido",
            options={"permissions": [("fechar_pedido", "Pode fechar pedidos")]},
        ),
    ]
